"""
Modal function definitions for Open-Inspect API.

These functions expose the sandbox management operations as
Modal functions that can be called from the control plane.

Note: Uses lazy imports to avoid pydantic dependency at module load time.
"""

from __future__ import annotations

import os
from typing import TYPE_CHECKING

from .app import app, function_image, github_app_secrets

if TYPE_CHECKING:
    from sandbox_runtime import McpServerConfig

# Global sandbox manager (lazy loaded)
_manager = None


def get_manager():
    """Get or create the sandbox manager instance."""
    global _manager
    if _manager is None:
        from .sandbox.manager import SandboxManager

        _manager = SandboxManager()
    return _manager


@app.function(image=function_image, secrets=[github_app_secrets])
async def create_sandbox(
    session_id: str,
    repo_owner: str,
    repo_name: str,
    control_plane_url: str,
    sandbox_auth_token: str,
    sandbox_id: str | None = None,
    snapshot_id: str | None = None,
    opencode_session_id: str | None = None,
    provider: str = "anthropic",
    model: str = "claude-sonnet-4-6",
    branch: str | None = None,
    mcp_servers: list[McpServerConfig] | None = None,
) -> dict:
    """
    Create a new sandbox for a session.

    Args:
        session_id: Unique session identifier
        repo_owner: GitHub repository owner
        repo_name: GitHub repository name
        control_plane_url: URL for control plane WebSocket
        sandbox_auth_token: Authentication token for sandbox
        sandbox_id: Expected sandbox ID (generated by control plane for auth)
        snapshot_id: Optional snapshot to restore from
        opencode_session_id: Optional existing OpenCode session ID
        provider: LLM provider (anthropic, openai)
        model: Model identifier

    Returns:
        dict with sandbox_id and status
    """
    # Lazy imports to avoid pydantic at module load time
    from .auth import generate_installation_token
    from .sandbox import SessionConfig
    from .sandbox.manager import SandboxConfig

    manager = get_manager()

    # Generate GitHub App token for git operations (sync, push)
    github_app_token = None
    try:
        app_id = os.environ.get("GITHUB_APP_ID")
        private_key = os.environ.get("GITHUB_APP_PRIVATE_KEY")
        installation_id = os.environ.get("GITHUB_APP_INSTALLATION_ID")

        if app_id and private_key and installation_id:
            github_app_token = generate_installation_token(
                app_id=app_id,
                private_key=private_key,
                installation_id=installation_id,
            )
    except Exception as e:
        # Log but don't fail - public repos can work without token
        print(f"Warning: Failed to generate GitHub App token: {e}")

    session_config = SessionConfig(
        session_id=session_id,
        repo_owner=repo_owner,
        repo_name=repo_name,
        branch=branch,
        opencode_session_id=opencode_session_id,
        provider=provider,
        model=model,
        mcp_servers=mcp_servers,
    )

    config = SandboxConfig(
        repo_owner=repo_owner,
        repo_name=repo_name,
        sandbox_id=sandbox_id,  # Use control-plane-provided ID for auth validation
        snapshot_id=snapshot_id,
        session_config=session_config,
        control_plane_url=control_plane_url,
        sandbox_auth_token=sandbox_auth_token,
        github_app_token=github_app_token,
    )

    handle = await manager.create_sandbox(config)

    return {
        "sandbox_id": handle.sandbox_id,
        "status": handle.status.value,
        "created_at": handle.created_at,
        "code_server_url": handle.code_server_url,
        "code_server_password": handle.code_server_password,
    }


@app.function(image=function_image)
async def warm_sandbox(
    repo_owner: str,
    repo_name: str,
    control_plane_url: str = "",
) -> dict:
    """
    Pre-warm a sandbox for faster startup.

    Called when user starts typing to reduce latency.

    Args:
        repo_owner: GitHub repository owner
        repo_name: GitHub repository name
        control_plane_url: Optional control plane URL

    Returns:
        dict with sandbox_id
    """
    manager = get_manager()
    handle = await manager.warm_sandbox(
        repo_owner=repo_owner,
        repo_name=repo_name,
        control_plane_url=control_plane_url,
    )

    return {
        "sandbox_id": handle.sandbox_id,
        "status": handle.status.value,
    }


# Health check endpoint
@app.function(image=function_image)
def health_check() -> dict:
    """Health check endpoint."""
    return {
        "status": "healthy",
        "service": "open-inspect-modal",
    }
